# Generated by Django 5.1 on 2024-08-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
