# Generated by Django 5.1 on 2024-08-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_review_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='photo',
        ),
        migrations.AddField(
            model_name='hotel',
            name='photoUrl',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
